import Head from "next/head";
import { H1 } from "~/components/typography";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import Map from "react-map-gl";
import { env } from "~/env.mjs";
import { useEffect, useState } from "react";

export default function Home() {
  const [viewState, setViewState] = useState({
    longitude: -120.6069,
    latitude: 45.2146,
    zoom: 11,
  });
  const [loading, setLoading] = useState(true);
  const [geoAvailable, setGeoAvailable] = useState(false);

  useEffect(() => {
    if ("geolocation" in navigator) {
      console.log("Geolaction Available");
      setGeoAvailable(true);
      navigator.geolocation.getCurrentPosition((position) => {
        setViewState((v) => ({
          ...v,
          longitude: position.coords.longitude,
          latitude: position.coords.latitude,
        }));
        setLoading(false);
      });
    } else {
      console.log("Not Available");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="container  flex flex-col place-items-center">
          <H1 className=" py-12">Potty Portal🚻</H1>
          <Card className="max-w-sm shadow-2xl shadow-violet-950">
            <CardHeader>
              <CardTitle>Potty Map</CardTitle>
              <CardDescription>
                Find, add, and rate public restrooms
              </CardDescription>
            </CardHeader>
            <CardContent className="">
              {!geoAvailable ? (
                <p>location not available</p>
              ) : loading ? (
                <p>loading</p>
              ) : (
                <div className="">
                  <Map
                    mapboxAccessToken={env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
                    initialViewState={{
                      latitude: viewState.latitude,
                      longitude: viewState.longitude,
                      zoom: viewState.zoom,
                    }}
                    onMove={(evt) => setViewState(evt.viewState)}
                    style={{
                      width: "100%",
                      height: "300px",
                      borderRadius: "10px",
                    }}
                    mapStyle="mapbox://styles/mapbox/streets-v11"
                  />
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </main>
    </>
  );
}
